name: Action push

on:
  push:
 

jobs:
  build:
    runs-on: ubuntu-latest

on:
  push:
    branches:
      - ${{ github.ref }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }} 
        ref: ${{ github.ref }}

    - name: Build with Maven

      run: mvn clean package --file hola-mundo/pom.xml

    - name: Test Build
      run: mvn test --file hola-mundo/pom.xml

    - name: Ejecutar el JAR
      run: mvn -f hola-mundo/pom.xml exec:java -Dexec.mainClass="com.ejemplo.App"      
