name: Build en DEV_JBCR

on:
  push:
    branches:
      - DEV_JBCR

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2
      with:
        repository: juliobautistaSFTK/TallerGITHUB
        ref: DEV_JBCR

    - name: Build with Maven
      run: mvn clean package --file hola-mundo/pom.xml

    - name: Contenido del JAR
      run: jar tf /home/runner/work/TallerGITHUB94/TallerGITHUB94/hola-mundo/target/hola-mundo-1.0-SNAPSHOT.jar

    - name: Extrae el MANIFEST
      run: jar xf /home/runner/work/TallerGITHUB94/TallerGITHUB94/hola-mundo/target/hola-mundo-1.0-SNAPSHOT.jar META-INF/MANIFEST.MF

    - name: muestra el MANIFEST
      run: cat META-INF/MANIFEST.MF

    - name: Donde estoy
      run: pwd        

    - name: Ejecutar el JAR
      run: mvn exec:java -Dexec.mainClass="hola-mundo/com.ejemplo.App"      
